import os
import uuid
import json
from datetime import datetime, timezone
from dotenv import load_dotenv
from flask import Flask, request, jsonify

load_dotenv()

app = Flask(__name__)

from groq import Groq

client = Groq(api_key=os.getenv("GROQ_API_KEY"))

def signal_groq(text):
    prompt = f"""You are an AI content detection system. Analyze the following text and determine whether it was written by a human or generated by an AI tool.

Return ONLY a JSON object in this exact format, nothing else:
{{"score": 0.0, "reasoning": "brief explanation"}}

Where score is a float between 0.0 and 1.0:
- 0.0 means you are certain it was written by a human
- 1.0 means you are certain it was generated by AI
- 0.5 means you are uncertain

Text to analyze:
{text}"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.1
    )

    raw = response.choices[0].message.content.strip()
    result = json.loads(raw)
    return result["score"]

import re
import statistics

def signal_stylometric(text):
    sentences = re.split(r'[.!?]+', text)
    sentences = [s.strip() for s in sentences if s.strip()]
    
    if len(sentences) < 2:
        variance_score = 0.5
    else:
        lengths = [len(s.split()) for s in sentences]
        variance = statistics.variance(lengths)
        variance_score = max(0.0, min(1.0, 1 - (variance / 40)))

    words = re.findall(r'\b\w+\b', text.lower())
    ttr = len(set(words)) / len(words) if words else 0.5
    ttr_score = max(0.0, min(1.0, 1 - ttr))

    stylometric_score = (variance_score * 0.7) + (ttr_score * 0.3)
    return round(stylometric_score, 3)

# ── Audit log (in-memory for now) ──────────────────────────────────────────
audit_log = []

def write_log(entry):
    audit_log.append(entry)

def get_log():
    return audit_log

# ── Routes ─────────────────────────────────────────────────────────────────
@app.route("/submit", methods=["POST"])
def submit():
    data = request.get_json()
    text = data.get("text", "")
    creator_id = data.get("creator_id", "anonymous")
    content_id = str(uuid.uuid4())

    # Signal 1: Groq LLM
    llm_score = signal_groq(text)

    # Signal 2: Stylometric heuristics
    stylo_score = signal_stylometric(text)

    # Combined confidence: Groq 70%, Stylometric 30%
    confidence = round((llm_score * 0.7) + (stylo_score * 0.3), 3)

    entry = {
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "attribution": "pending",
        "confidence": confidence,
        "llm_score": llm_score,
        "stylo_score": stylo_score,
        "status": "classified"
    }
    write_log(entry)

    return jsonify({
        "content_id": content_id,
        "attribution": "pending",
        "confidence": confidence,
        "llm_score": llm_score,
        "stylo_score": stylo_score,
        "label": "Processing..."
    })

@app.route("/log", methods=["GET"])
def log():
    return jsonify({"entries": get_log()})

if __name__ == "__main__":
    app.run(debug=True)