import os
import uuid
import json
import re
import statistics
from datetime import datetime, timezone
from dotenv import load_dotenv
from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq

load_dotenv()

app = Flask(__name__)

limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

client = Groq(api_key=os.getenv("GROQ_API_KEY"))

# ── Signal 1: Groq LLM ─────────────────────────────────────────────────────
def signal_groq(text):
    prompt = f"""You are an AI content detection system. Analyze the following text and determine whether it was written by a human or generated by an AI tool.

Return ONLY a JSON object in this exact format, nothing else:
{{"score": 0.0, "reasoning": "brief explanation"}}

Where score is a float between 0.0 and 1.0:
- 0.0 means you are certain it was written by a human
- 1.0 means you are certain it was generated by AI
- 0.5 means you are uncertain

Text to analyze:
{text}"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.1
    )
    raw = response.choices[0].message.content.strip()
    result = json.loads(raw)
    return result["score"]

# ── Signal 2: Stylometric Heuristics ───────────────────────────────────────
def signal_stylometric(text):
    sentences = re.split(r'[.!?]+', text)
    sentences = [s.strip() for s in sentences if s.strip()]

    if len(sentences) < 2:
        variance_score = 0.5
    else:
        lengths = [len(s.split()) for s in sentences]
        variance = statistics.variance(lengths)
        variance_score = max(0.0, min(1.0, 1 - (variance / 40)))

    words = re.findall(r'\b\w+\b', text.lower())
    ttr = len(set(words)) / len(words) if words else 0.5
    ttr_score = max(0.0, min(1.0, 1 - ttr))

    stylometric_score = (variance_score * 0.7) + (ttr_score * 0.3)
    return round(stylometric_score, 3)

# ── Transparency Label ──────────────────────────────────────────────────────
def generate_label(confidence):
    if confidence >= 0.70:
        return (
            "Our system has determined that this content was likely generated by an AI tool. "
            "This label is based on an analysis of writing patterns and style. "
            "If you are the creator and believe this is incorrect, you can submit an appeal."
        )
    elif confidence >= 0.40:
        return (
            "Our system was unable to make a confident determination about whether this content "
            "was written by a human or generated by AI. The signals were mixed. "
            "If you are the creator and believe this label is inaccurate, you can submit an appeal."
        )
    else:
        return (
            "Our system has determined that this content was likely written by a human. "
            "This label is based on an analysis of writing patterns and style."
        )

# ── Audit Log ───────────────────────────────────────────────────────────────
audit_log = []

def write_log(entry):
    audit_log.append(entry)

def get_log():
    return audit_log

# ── Routes ──────────────────────────────────────────────────────────────────
@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    data = request.get_json()
    text = data.get("text", "")
    creator_id = data.get("creator_id", "anonymous")
    content_id = str(uuid.uuid4())

    llm_score = signal_groq(text)
    stylo_score = signal_stylometric(text)
    confidence = round((llm_score * 0.7) + (stylo_score * 0.3), 3)
    label = generate_label(confidence)

    if confidence >= 0.70:
        attribution = "likely_ai"
    elif confidence >= 0.40:
        attribution = "uncertain"
    else:
        attribution = "likely_human"

    entry = {
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": llm_score,
        "stylo_score": stylo_score,
        "status": "classified"
    }
    write_log(entry)

    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": llm_score,
        "stylo_score": stylo_score,
        "label": label
    })

@app.route("/appeal", methods=["POST"])
def appeal():
    data = request.get_json()
    content_id = data.get("content_id", "")
    creator_reasoning = data.get("creator_reasoning", "")

    if not content_id:
        return jsonify({"error": "content_id is required"}), 400

    updated = False
    for entry in audit_log:
        if entry["content_id"] == content_id:
            entry["status"] = "under_review"
            entry["appeal_reasoning"] = creator_reasoning
            entry["appeal_timestamp"] = datetime.now(timezone.utc).isoformat()
            updated = True
            break

    if not updated:
        return jsonify({"error": "content_id not found"}), 404

    return jsonify({
        "message": "Your appeal has been received and is under review.",
        "content_id": content_id,
        "status": "under_review"
    })

@app.route("/log", methods=["GET"])
def log():
    return jsonify({"entries": get_log()})

if __name__ == "__main__":
    app.run(debug=True)